server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: servicio-venta
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
