server:
  port: 8081
spring:
  application:
    name: servicio-producto
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/proyecto_bisa
    username: postgres
    password: 1234
